"""Process all Huawei VRP log files from the logs/ folder into screenshots.

Configuration is read from run_config.json in the same directory.
If run_config.json is missing, a template will be auto-generated.

Whitelist behavior:
  - If whitelist is empty/null: all commands are processed (backward-compatible)
  - If whitelist has items: only matching commands (standalone or nested blocks
    containing at least one matching command) are rendered to PNG.
"""
import argparse
import asyncio
import json
import multiprocessing
import os
import sys
import glob
import time

import process_network_logs

def get_base_dir():
    """Get the directory where the .exe or .py script lives."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))

SCRIPT_DIR = get_base_dir()
CONFIG_PATH = os.path.join(SCRIPT_DIR, "run_config.json")

_DEFAULT_CONFIG = {
    "logs_dir": "logs",
    "output_dir": "screenshots",
    "whitelist": [],
    "font_size": 6,
    "line_height": 1.3,
    "workers": 4,
    "batch_size": 25
}


def _ensure_config():
    """If run_config.json is missing, create a template and exit."""
    if os.path.exists(CONFIG_PATH):
        return
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(_DEFAULT_CONFIG, f, indent=2, ensure_ascii=False)
    print(f"Created template: {CONFIG_PATH}")
    print("Please edit it with your paths and whitelist, then run again.")
    sys.exit(0)


def load_config():
    """Read and validate run_config.json."""
    _ensure_config()
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    whitelist = cfg.get("whitelist") or []
    if not isinstance(whitelist, list):
        print("WARNING: 'whitelist' must be a list; using empty whitelist (process all commands).")
        whitelist = []

    # Normalize whitelist to lowercase for case-insensitive exact matching
    whitelist = [str(cmd).strip().lower() for cmd in whitelist if str(cmd).strip()]

    logs_dir = cfg.get("logs_dir", "logs")
    output_dir = cfg.get("output_dir", "screenshots")
    return logs_dir, output_dir, whitelist


def _process_chunk(args):
    """Worker function for multiprocessing.Pool. MUST be at module level for Windows spawn.

    Reads log files from the chunk, builds ``(content, basename)`` tuples,
    then calls ``generate_screenshots_batched`` to parse and render screenshots.

    Parameters
    ----------
    args : tuple
        ``(chunk_files, output_dir, whitelist, batch_size, worker_id)``

    Returns
    -------
    int
        Number of screenshots generated by this worker.
    """
    chunk_files, output_dir, whitelist, batch_size, worker_id = args
    file_list = []
    for file_path in chunk_files:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        file_list.append((content, os.path.basename(file_path)))

    if not file_list:
        return 0

    results = asyncio.run(
        process_network_logs.generate_screenshots_batched(
            file_list, output_dir, whitelist,
            batch_size=batch_size, worker_id=worker_id
        )
    )
    return len(results)


def main():
    logs_dir_name, output_dir_name, whitelist = load_config()

    # Resolve workers + batch_size from limits (validated / capped by load_limits)
    limits = process_network_logs.load_limits(CONFIG_PATH)
    default_workers = limits["workers"]
    default_batch_size = limits["batch_size"]

    # CLI override for workers
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--workers", type=int, default=None,
        help=f"Number of worker processes (default: {default_workers})"
    )
    cli_args, _ = parser.parse_known_args()
    workers = cli_args.workers if cli_args.workers is not None else default_workers

    logs_dir = os.path.join(SCRIPT_DIR, logs_dir_name)
    output_dir = os.path.join(SCRIPT_DIR, output_dir_name)

    if not os.path.isdir(logs_dir):
        print(f"[ERROR] logs directory not found at {logs_dir}")
        sys.exit(1)

    # Clean up old PNG files once before processing all logs
    if os.path.exists(output_dir):
        for f in os.listdir(output_dir):
            if f.endswith('.png'):
                os.remove(os.path.join(output_dir, f))
    else:
        os.makedirs(output_dir, exist_ok=True)

    log_files = sorted(
        os.path.join(logs_dir, f)
        for f in os.listdir(logs_dir)
        if f.lower().endswith(('.txt', '.log')) and os.path.isfile(os.path.join(logs_dir, f))
    )

    if not log_files:
        print(f"[WARN] No .txt or .log files found in {logs_dir}")
        sys.exit(1)

    start_time = time.time()

    if workers == 1:
        # Sequential fallback: read all files, process in one batched call
        file_list = []
        for log_path in log_files:
            with open(log_path, "r", encoding="utf-8") as f:
                content = f.read()
            file_list.append((content, os.path.basename(log_path)))
        results = asyncio.run(
            process_network_logs.generate_screenshots_batched(
                file_list, output_dir, whitelist,
                batch_size=default_batch_size
            )
        )
        total = len(results)
    else:
        # Round-robin chunking: distribute log files across workers
        chunks = [[] for _ in range(workers)]
        for i, f in enumerate(log_files):
            chunks[i % workers].append(f)
        # Remove empty chunks (e.g., fewer files than workers)
        chunks = [c for c in chunks if c]
        num_workers = min(workers, len(chunks))

        with multiprocessing.Pool(processes=num_workers) as pool:
            task_args = [
                (chunk, output_dir, whitelist, default_batch_size, f"w{i}")
                for i, chunk in enumerate(chunks)
            ]
            counts = pool.map(_process_chunk, task_args)
        total = sum(counts)

    # Merge per-worker truncated-command logs
    process_network_logs.aggregate_truncated_logs(output_dir)

    elapsed = time.time() - start_time
    whitelist_msg = f" (whitelist: {whitelist})" if whitelist else ""
    print(f"\n[DONE] {total} total screenshots from {len(log_files)} log files "
          f"using {workers} worker(s) in {elapsed:.1f}s{whitelist_msg}")


if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
